---
project_name: kube-volume-cleaner
builds:
  - main: ./main.go
    binary: kube-volume-cleaner
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
archives:
  - format: binary
    files:
      - none*
    replacements:
      386: i386
      amd64: x86_64
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "mohmann/kube-volume-cleaner:latest"
      - "mohmann/kube-volume-cleaner:{{ .Tag }}"
      - "mohmann/kube-volume-cleaner:v{{ .Major }}"
    binaries:
      - kube-volume-cleaner
release:
  github:
    owner: martinohmann
    name: kube-volume-cleaner
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
